/*
 * Copyright (c) 2020 Microsoft. All rights reserved.
 */

// This tool takes a private key in PEM format and exports a public key
// generated from it. It is exported in both binary and C array formats.
//
// To use it:
//
//     keytool PRIVATE_KEY_PEM.txt output_binary.bin output_c.c

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>

#include "crypto/ImageSigning.h"
#include "crypto/crypto_files.h"

static int save_bin(const char *path, fw_pub_key *pub_key) {
  FILE *f = fopen(path, "wb");
  if (f == NULL) {
    printf("Couldn't open %s for writing\n", path);
    return -1;
  }

  if (fwrite(pub_key->data, sizeof(fw_pub_key), 1, f) != 1) {
    printf("Failed to write data to %s\n", path);
    fclose(f);
    return -1;
  }

  fclose(f);

  return 0;
}

static int save_c_array(const char *path, const char *arrayname,
                        fw_pub_key *pub_key) {
  FILE *f = fopen(path, "wb");
  if (f == NULL) {
    printf("Couldn't open %s for writing\n", path);
    return -1;
  }

  fprintf(f, "/*\n");
  fprintf(f, " * Copyright (c) 2020 Microsoft. All rights reserved.\n");
  fprintf(f, " */\n");
  fprintf(f, "\n");
  fprintf(f, "// This file is autogenerated by keytool. Do not edit.\n");
  fprintf(f, "\n");
  fprintf(f, "#include \"crypto/ImageSigning.h\"\n");
  fprintf(f, "\n");
  fprintf(f, "const fw_pub_key %s = { .data = {\n", arrayname);

  fprintf(f, "    0x%02X,", pub_key->data[0]);

  for (size_t i = 0; i < sizeof(fw_pub_key) - 1; i++) {
    if (i % 8 == 0)
      fprintf(f, "\n    ");
    else
      fprintf(f, " ");

    fprintf(f, "0x%02X,", pub_key->data[i + 1]);
  }
  fprintf(f, "\n");
  fprintf(f, "}};\n");

  fclose(f);

  return 0;
}

static void print_usage(const char *argv0) {
  printf("Usage: %s key.txt output.bin output.c\n", argv0);
}

int main(int argc, char *argv[]) {
  if (argc != 5) {
    printf("Missing arguments.\n");
    print_usage(argv[0]);
    exit(EXIT_FAILURE);
  }

  const char *key_path = argv[1];
  const char *out_bin_path = argv[2];
  const char *c_array_path = argv[3];
  const char *arrayname = argv[4];

  fw_priv_key priv_key;
  fw_pub_key pub_key;

  int ret;

  ret = crypto_load_priv_key(key_path, &priv_key);
  if (ret != 0) {
    printf("Failed to load private key: %d\n", ret);
    exit(EXIT_FAILURE);
  }

  ret = crypto_gen_pub_key(&pub_key, &priv_key);
  if (ret != 0) {
    printf("Failed to generate public key: %d\n", ret);
    exit(EXIT_FAILURE);
  }

  ret = save_bin(out_bin_path, &pub_key);
  if (ret != 0) {
    printf("Failed to save binary file: %d\n", ret);
    exit(EXIT_FAILURE);
  }

  ret = save_c_array(c_array_path, arrayname, &pub_key);
  if (ret != 0) {
    printf("Failed to save C array: %d\n", ret);
    exit(EXIT_FAILURE);
  }

  exit(EXIT_SUCCESS);
}
