/*
 * Copyright (c) 2020 Microsoft. All rights reserved.
 */

#pragma once

#define ORGANIZATION "Microsoft"
#define CITY "Bangalore"
#define COUNTRY "IN"

#define ALIAS_SUBJECT_COMMON_NAME "Alias Key"
#define ALIAS_SUBJECT_ORGANIZATION ORGANIZATION
#define ALIAS_SUBJECT_CITY CITY
#define ALIAS_SUBJECT_COUNTRY COUNTRY

#define DEVICE_SUBJECT_COMMON_NAME "Device Identity"
#define DEVICE_SUBJECT_ORGANIZATION ORGANIZATION
#define DEVICE_SUBJECT_CITY CITY
#define DEVICE_SUBJECT_COUNTRY COUNTRY
